techpack: display: msm: sde: Squashed reverts of avoid race condition at vm release
Fixes:
../../../../../../kernel/samsung/a23xq/techpack/display/msm/sde/sde_kms.c:1389:13: error: redefinition of 'sde_kms_cancel_delayed_work'
 1389 | static void sde_kms_cancel_delayed_work(struct drm_crtc *crtc)
      |             ^
../../../../../../kernel/samsung/a23xq/techpack/display/msm/sde/sde_kms.c:1323:13: note: previous definition is here
 1323 | static void sde_kms_cancel_delayed_work(struct drm_crtc *crtc)
      |             ^
../../../../../../kernel/samsung/a23xq/techpack/display/msm/sde/sde_kms.c:1414:5: error: redefinition of 'sde_kms_vm_pre_release'
 1414 | int sde_kms_vm_pre_release(struct sde_kms *sde_kms,
      |     ^
../../../../../../kernel/samsung/a23xq/techpack/display/msm/sde/sde_kms.c:1348:5: note: previous definition is here
 1348 | int sde_kms_vm_pre_release(struct sde_kms *sde_kms,

Revert "techpack: display: msm: sde: flush pp event work queue before vm release"

This reverts commit d98745586c6eca98e835ae7b10f543dc06495397.

Revert "techpack: display: msm: sde: flush event thread workqueue before vm release"

This reverts commit b0b58de57dc32227da066798cd32ab3a09339067.

Revert "techpack: display: msm: sde: avoid race condition at vm release"

This reverts commit 081a4884aabd61b6786262dba4c1b7ff9577b1f5.

Change-Id: I3a89a0375440145f6ae92517f6da2f5adf279458